### ISSUE TITLE
2.0.0 of the AWS Cloudformation Specification breaks cfndsl

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#370]
```
/Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/types.rb:63:in `block (2 levels) in included': uninitialized constant CfnDsl::AWS::Types::AWSEC2LaunchTemplateTag (NameError)
Did you mean?  CfnDsl::AWS::Types::AWSEC2LaunchTemplateLaunchTemplateData
               CfnDsl::AWS::Types::AWSEC2LaunchTemplatePlacement
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateElasticGpuSpecification
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateTagSpecification
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateInstanceMarketOptions
               CfnDsl::AWS::Types::AWSEC2SpotFleetLaunchTemplateConfig
               CfnDsl::AWS::Types::AWSEC2LaunchTemplatePrivateIpAdd
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateBlockDeviceMapping
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateIamInstanceProfile
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateCreditSpecification
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateMonitoring
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateNetworkInterface
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateSpotOptions
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateEbs
               CfnDsl::AWS::Types::AWSEC2LaunchTemplateIpv6Add
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/types.rb:61:in `each_pair'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/types.rb:61:in `block in included'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/types.rb:58:in `each_pair'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/types.rb:58:in `included'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/types.rb:9:in `include'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/types.rb:9:in `<module:Types>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/types.rb:6:in `<module:AWS>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/types.rb:4:in `<module:CfnDsl>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/types.rb:3:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/orchestration_template.rb:3:in `require'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/orchestration_template.rb:3:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/cloud_formation_template.rb:1:in `require'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl/aws/cloud_formation_template.rb:1:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl.rb:20:in `require'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/lib/cfndsl.rb:20:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/bin/cfndsl:135:in `require'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/gems/cfndsl-0.16.3/bin/cfndsl:135:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/bin/cfndsl:23:in `load'
	from /Users/gregc/.rvm/gems/ruby-2.3.1/bin/cfndsl:23:in `<main>'
```

**Comment by gergnz** [comment]
The Tag specification is inconsistent between properties

```
    "AWS::EC2::SpotFleet.SpotFleetTagSpecification": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-tagspecifications.html",
      "Properties": {
        "ResourceType": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-tagspecifications.html#cfn-ec2-spotfleet-spotfleettagspecification-resourcetype",
          "PrimitiveType": "String",
          "Required": false,
          "UpdateType": "Mutable"
        }
      }
    }
```

```
    "AWS::EC2::LaunchTemplate.TagSpecification": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html",
      "Properties": {
        "ResourceType": {
          "Required": false,
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html#cfn-ec2-launchtemplate-tagspecification-resourcetype",
          "PrimitiveType": "String",
          "UpdateType": "Mutable"
        },
        "Tags": {
          "Type": "List",
          "Required": false,
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html#cfn-ec2-launchtemplate-tagspecification-tags",
          "ItemType": "Tag",
          "UpdateType": "Mutable"
        }
      }
    }
```

If we remove the Tags from the LaunchTemplate it works again.
```
 diff original.json resource_specification.json
8876a8877,8883
>         },
>         "Tags": {
>           "Type": "List",
>           "Required": false,
>           "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html#cfn-ec2-launchtemplate-tagspecification-tags",
>           "ItemType": "Tag",
>           "UpdateType": "Mutable"
```

**Comment by gergnz** [comment]
I've pinged AWS support to see if we can get information out of the Cloudformation team on this one, but wondering if we need to cope better with this scenario somehow.
