### ISSUE TITLE
'require': cannot load such file -- hana (0.17.pre.5)

### ISSUE THREAD

**Issue by cfarrend** [cfndsl/cfndsl#387]
Got this error when trying to generate a template with only the cfndsl (0.17.pre.5) gem
```
Traceback (most recent call last):
	10: from /usr/local/bin/cfndsl:23:in `<main>'
	 9: from /usr/local/bin/cfndsl:23:in `load'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.pre.5/bin/cfndsl:137:in `<top (required)>'
	 7: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.pre.5/lib/cfndsl.rb:20:in `<top (required)>'
	 4: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.pre.5/lib/cfndsl/specification.rb:3:in `<top (required)>'
	 1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- hana (LoadError)
```
```
Gems included by the bundle:
  * bundler (1.16.6)
  * cfndsl (0.17.pre.5)
```

I had to install the 'hana' gem to get it to work.
```
Gems included by the bundle:
  * bundler (1.16.6)
  * cfndsl (0.17.pre.5)
  * hana (1.3.4)
```

**Comment by gergnz** [comment]
Should be fixed in 0.17.pre.6.
