### ISSUE TITLE
cfndsl fails with "uninitialized constant CfnDsl::AWS::Types::AWSWAFv2IPSetTag (NameError)"

### ISSUE THREAD

**Issue by Line-Noise** [cfndsl/cfndsl#430]
After updating the specification file cfndsl 0.17.4 fails with the following message:

```
Traceback (most recent call last):
        23: from /usr/local/bundle/bin/cfndsl:23:in `<main>'
        22: from /usr/local/bundle/bin/cfndsl:23:in `load'
        21: from /usr/local/bundle/gems/cfndsl-0.17.4/bin/cfndsl:143:in `<top (required)>'
        20: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        18: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl.rb:23:in `<top (required)>'
        17: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/cloud_formation_template.rb:3:in `<top (required)>'
        14: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/orchestration_template.rb:5:in `<top (required)>'
        11: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/types.rb:5:in `<top (required)>'
         8: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/types.rb:6:in `<module:CfnDsl>'
         7: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/types.rb:8:in `<module:AWS>'
         6: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/types.rb:11:in `<module:Types>'
         5: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/aws/types.rb:11:in `include'
         4: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/types.rb:60:in `included'
         3: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/types.rb:60:in `each_pair'
         2: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/types.rb:64:in `block in included'
         1: from /usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/types.rb:64:in `each_pair'
/usr/local/bundle/gems/cfndsl-0.17.4/lib/cfndsl/types.rb:66:in `block (2 levels) in included': uninitialized constant CfnDsl::AWS::Types::AWSWAFv2IPSetTag (NameError)
Did you mean?  CfnDsl::AWS::Types::AWSWAFv2IPSetTagList
```

Amazon have updated things: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html

> This is the latest version of AWS WAF, named AWS WAFV2, released in November, 2019.

**Comment by adrianmace** [comment]
+1 I am also having this issue.

**Comment by gergnz** [comment]
Hi @adrianmace and @Line-Noise,

Thanks for the reports. I'll wait until the end of the week to see if there are any other services, features, etc, that are released as part of re:invent, and I will add support all in one go.

Thanks for your patience.

**Comment by Line-Noise** [comment]
No problem. Pinning the version of the specification file during update is a valid workaround.

`cfndsl --update-specification 8.1.0`

**Comment by sneh-shah** [comment]
+1 facing this issue

**Comment by Samseppiol** [comment]
+1
