### ISSUE TITLE
undefined method `EC2_LaunchTemplate' for #<CfnDsl::CloudFormationTemplate:...> (NoMethodError)

### ISSUE THREAD

**Issue by behrangsa** [cfndsl/cfndsl#431]
Out of the box compilation of this template fails:

```ruby
# frozen_string_literal: true

require 'cfndsl'

CloudFormation do
    EC2_LaunchTemplate(:Sample) do
        
    end
end
```

with this error:

```
test.rb:6:in `block in eval_file_with_extras': undefined method `EC2_LaunchTemplate' for #<CfnDsl::CloudFormationTemplate:0x000000024370e0> (NoMethodError)
Did you mean?  eC2_VolumeAttachment
```

If I update the specification to the latest version, it will fail with:

```
types.rb:66:in `block (2 levels) in included': uninitialized constant CfnDsl::AWS::Types::AWSWAFv2IPSetTag (NameError)
Did you mean?  CfnDsl::AWS::Types::AWSWAFv2IPSetTagList
```

However it is listed as a supported type:

```
$ cfndsl -l | grep LaunchTemplate
AWS::EC2::LaunchTemplate
AWS::ServiceCatalog::LaunchTemplateConstraint
```

**Comment by behrangsa** [comment]
This seems to be a duplicate of https://github.com/cfndsl/cfndsl/issues/430. Closing.
