### ISSUE TITLE
Resources ["Foo"] refer to unknown Reference AWS::Partition

### ISSUE THREAD

**Issue by behrangsa** [cfndsl/cfndsl#444]
Looks like cfndsl doesn't like the `AWS::Partition` pseudo parameter:

```
❯ cfndsl --version
cfndsl 1.0.1

/tmp via 💎 v2.3.7 on ☁️  saml(ap-southeast-2)
❯ cat foo.rb
CloudFormation do
  Lambda_Permission('Foo') do
    SourceArn FnJoin(':', ['arn',
                           Ref('AWS::Partition'),
                          'logs',
                           Ref('AWS::Region'),
                           Ref('AWS::AccountId'),
                           'log-group',
                           FnJoin('', ['/aws/lambda/', 'foo']), '*'])
  end
end


/tmp via 💎 v2.3.7 on ☁️  saml(ap-southeast-2)
❯ cfndsl foo.rb
/Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/orchestration_template.rb:285:in `validate': 1 errors in template (CfnDsl::Error)
Invalid Reference: Resources ["Foo"] refer to unknown Reference AWS::Partition
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:113:in `CloudFormation'
	from /private/tmp/foo.rb:1:in `eval_file_with_extras'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:57:in `eval'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:57:in `eval_file_with_extras'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/runner.rb:124:in `invoke!'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/exe/cfndsl:5:in `<top (required)>'
	from /Users/Scooby/.gem/ruby/2.3.0/bin/cfndsl:22:in `load'
	from /Users/Scooby/.gem/ruby/2.3.0/bin/cfndsl:22:in `<main>'

/tmp via 💎 v2.3.7 on ☁️  saml(ap-southeast-2)
❯
```

**Comment by behrangsa** [comment]
Looks like updating the specification file fixes the problem.

**Comment by behrangsa** [comment]
Not consistently:

```
> jq .ResourceSpecificationVersion ~/.cfndsl/resource_specification.json
"11.1.0"

❯ cfndsl -s ~/.cfndsl/resource_specification.json foo.rb
/Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/orchestration_template.rb:285:in `validate': 1 errors in template (CfnDsl::Error)
Invalid Reference: Resources ["Foo"] refer to unknown Reference AWS::Partition
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:113:in `CloudFormation'
	from /private/tmp/foo.rb:1:in `eval_file_with_extras'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:57:in `eval'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/cloudformation.rb:57:in `eval_file_with_extras'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/lib/cfndsl/runner.rb:124:in `invoke!'
	from /Users/Scooby/.gem/ruby/2.3.0/gems/cfndsl-1.0.1/exe/cfndsl:5:in `<top (required)>'
	from /Users/Scooby/.gem/ruby/2.3.0/bin/cfndsl:22:in `load'
	from /Users/Scooby/.gem/ruby/2.3.0/bin/cfndsl:22:in `<main>'
```

**Comment by gergnz** [comment]
> Looks like updating the specification file fixes the problem.

When you say the Specification fixes it, but then later say it's inconsistent (with two different ruby versions) it seems they both fail? 2.6.3 just has better output?

Also:
`cfndsl -a` will give you spec version

**Comment by behrangsa** [comment]
I think they both fail, irrespective of the Ruby/Spec version.
