### ISSUE TITLE
Issue with DSL generation from cli arguments

### ISSUE THREAD

**Issue by otakusid** [cfndsl/cfndsl#449]
I use cfndsl v.: 1.0.2 and when I try to generate DSL for CloudFormation resource type - receive an error `runner.rb:69:in 'block (2 levels) in invoke!: undefined method '<<' for nil:NilClass (NoMethodError)`

```
> bundler exec cfndsl -g AWS::Route53::RecordSet,RecordSet
Traceback (most recent call last):
        10: from D:/_work/lab.cloudformation-ssl/.vendor/bundle/bin/cfndsl:23:in `<main>'
         9: from D:/_work/lab.cloudformation-ssl/.vendor/bundle/bin/cfndsl:23:in `load'
         8: from D:/_work/lab.cloudformation-ssl/.vendor/bundle/gems/cfndsl-1.0.2/exe/cfndsl:5:in `<top (required)>'
         7: from c:/_work/lab.cloudformation-ssl/.vendor/bundle/gems/cfndsl-1.0.2/lib/cfndsl/runner.rb:90:in `invoke!'
         6: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1648:in `parse!'
         5: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1626:in `permute!'
         4: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1532:in `order!'
         3: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1538:in `parse_in_order'
         2: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1538:in `catch'
         1: from C:/tools/ruby25/lib/ruby/2.5.0/optparse.rb:1584:in `block in parse_in_order'
c:/_work/lab.cloudformation-ssl/.vendor/bundle/gems/cfndsl-1.0.2/lib/cfndsl/runner.rb:69:in `block (2 levels) in invoke!': undefined method `<<' for nil:NilClass (NoMethodError)
```

**Comment by gergnz** [comment]
Thanks for reporting this, I'll take a look.
