### ISSUE TITLE
unknown type AWSResourceGroupsGroupJson

### ISSUE THREAD

**Issue by gdlx** [cfndsl/cfndsl#453]
When updating the specifications file to a version >= 12.0.0, I receive the following error:
````
gdlx:~$ cfndsl -u 12.0.0
Updating specification file
Specification 12.0.0 successfully written to /home/gdlx/.cfndsl/resource_specification.json
gdlx:~$ cfndsl test.rb
unknown type AWSResourceGroupsGroupJson
Traceback (most recent call last):
        17: from /home/gdlx/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        16: from /home/gdlx/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
        15: from /home/gdlx/.rvm/gems/ruby-2.6.1/bin/cfndsl:23:in `<main>'
        14: from /home/gdlx/.rvm/gems/ruby-2.6.1/bin/cfndsl:23:in `load'
        13: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/exe/cfndsl:5:in `<top (required)>'
        12: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/runner.rb:125:in `invoke!'
        11: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/runner.rb:125:in `require_relative'
        10: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/cloudformation.rb:5:in `<top (required)>'
         9: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/cloudformation.rb:5:in `require_relative'
         8: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/aws/cloud_formation_template.rb:6:in `<top (required)>'
         7: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/aws/cloud_formation_template.rb:8:in `<module:CfnDsl>'
         6: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/aws/cloud_formation_template.rb:23:in `<class:CloudFormationTemplate>'
         5: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:43:in `create_types'
         4: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:43:in `each_pair'
         3: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:44:in `block in create_types'
         2: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:74:in `create_resource_def'
         1: from /home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:74:in `each_pair'
/home/gdlx/.rvm/gems/ruby-2.6.1/gems/cfndsl-1.0.5/lib/cfndsl/orchestration_template.rb:76:in `block in create_resource_def': uninitialized constant CfnDsl::AWS::Types::AWSResourceGroupsGroupJson (NameError)
Did you mean?  CfnDsl::AWS::Types::AWS_ResourceGroups_Group
               CfnDsl::AWS::Types::AWSResourceGroupsGroupQuery
````

My `test.rb` file is as simple as that:
````
CloudFormation do
end
````

When trying with a version < 12.0.0, I get no error:
````
gdlx:~$ cfndsl -u 11.0.0
Updating specification file
Specification 11.0.0 successfully written to /home/gdlx/.cfndsl/resource_specification.json
gdlx:~$ cfndsl test.rb
{"AWSTemplateFormatVersion":"2010-09-09"}
````

I have the same issue with 13.0.0 which is the latest  version. I just checked 11 & 12 to find when it stopped working.

**Comment by gergnz** [comment]
Thanks @gdlx I'll take a look.
