### ISSUE TITLE
List ItemType in the specification file breaking template generation with spec version 69.0.0

### ISSUE THREAD

**Issue by Guslington** [cfndsl/cfndsl#474]
AWS has introduced a List ItemType in the specification file for the `PolygonRegionsOfInterest` property in the `AWS::Rekognition::StreamProcessor` resource in spec version `69.0.0`

```json
...
    "AWS::Rekognition::StreamProcessor": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rekognition-streamprocessor.html",
      "Properties": {
        ...
        "PolygonRegionsOfInterest": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rekognition-streamprocessor.html#cfn-rekognition-streamprocessor-polygonregionsofinterest",
          "UpdateType": "Immutable",
          "Required": false,
          "Type": "List",
          "ItemType": "List",
          "DuplicatesAllowed": false
        },
```

The issues causes the following error

```
unknown type AWSRekognitionStreamProcessorList
Traceback (most recent call last):
	15: from /Users/gus/.rbenv/versions/2.7.2/bin/cfndsl:23:in `<main>'
	14: from /Users/gus/.rbenv/versions/2.7.2/bin/cfndsl:23:in `load'
	13: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/exe/cfndsl:5:in `<top (required)>'
	12: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/runner.rb:124:in `invoke!'
	11: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/runner.rb:124:in `require_relative'
	10: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/cloudformation.rb:5:in `<top (required)>'
	 9: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/cloudformation.rb:5:in `require_relative'
	 8: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/aws/cloud_formation_template.rb:6:in `<top (required)>'
	 7: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/aws/cloud_formation_template.rb:8:in `<module:CfnDsl>'
	 6: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/aws/cloud_formation_template.rb:23:in `<class:CloudFormationTemplate>'
	 5: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:43:in `create_types'
	 4: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:43:in `each_pair'
	 3: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:44:in `block in create_types'
	 2: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:74:in `create_resource_def'
	 1: from /Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:74:in `each_pair'
/Users/gus/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cfndsl-1.3.3/lib/cfndsl/orchestration_template.rb:86:in `block in create_resource_def': uninitialized constant CfnDsl::AWS::Types::AWSRekognitionStreamProcessorList (NameError)
Did you mean?  CfnDsl::AWS::Types::AWSRekognitionStreamProcessorPoint
               CfnDsl::AWS::Types::AWS_Rekognition_StreamProcessor
```

**Comment by gergnz** [comment]
Released in #1.3.4.
